name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build --------- -t  .
      - name: Publish image to docker hub
        run: docker push --------:latest   

  deploy: 
    needs: build
    runs-on: ec2-runner    
    steps:
      - name: Pull image from docker hub
        run: docker pull ------------- :latest 
      - name: Delete Old Container
        run: docker rm -f "previous container"
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer --------------------   
